
//----------------------------------------------------
//The following code was generated by CUP v0.10k
//Thu Feb 03 16:03:33 EST 2005
//----------------------------------------------------

package com.tonbeller.jpivot.olap.mdxparse;

/** CUP generated class containing symbol constants. */
public class sym {
/* terminals */
public static final int WHEN = 23;
public static final int WITH = 26;
public static final int GE = 33;
public static final int CONCAT = 30;
public static final int ASTERISK = 27;
public static final int EMPTY = 10;
public static final int DIMENSION = 7;
public static final int XOR = 25;
public static final int CASE = 4;
public static final int LPAREN = 37;
public static final int QUOTED_ID = 47;
public static final int MINUS = 39;
public static final int WHERE = 24;
public static final int RPAREN = 43;
public static final int NOT = 15;
public static final int AND = 2;
public static final int LT = 38;
public static final int OR = 17;
public static final int COMMA = 29;
public static final int NON = 14;
public static final int ON = 16;
public static final int SELECT = 20;
public static final int PLUS = 41;
public static final int QUOTE = 19;
public static final int MEMBER = 13;
public static final int ID = 46;
public static final int DOT = 31;
public static final int LE = 36;
public static final int EOF = 0;
public static final int DRILLTHROUGH = 8;
public static final int error = 1;
public static final int NUMBER = 45;
public static final int UNKNOWN = 50;
public static final int EQ = 32;
public static final int FROM = 12;
public static final int SOLIDUS = 44;
public static final int CELL_ORDINAL = 6;
public static final int COLON = 28;
public static final int LBRACE = 35;
public static final int ELSE = 9;
public static final int PROPERTIES = 18;
public static final int RBRACE = 42;
public static final int THEN = 22;
public static final int NE = 40;
public static final int END = 11;
public static final int STRING = 49;
public static final int AMP_QUOTED_ID = 48;
public static final int CELL = 5;
public static final int AS = 3;
public static final int GT = 34;
public static final int SET = 21;
}

